// This file contains action types

/* For giving user authorization */

export const AUTH_STATUS = {
  AUTH_STATUS_TOKEN_FOUND: "AUTH_STATUS_TOKEN_FOUND",
  AUTH_STATUS_TOKEN_FETCHING: "AUTH_STATUS_TOKEN_FETCHING",
  AUTH_STATUS_TOKEN_ERROR: "AUTH_STATUS_TOKEN_ERROR",
};

/* For fetching all products info */

export const ALL_PRODUCTS = {
  ALL_PRODUCTS_LOADED: "ALL_PRODUCTS_LOADED",
  ALL_PRODUCTS_ERROR: "ALL_PRODUCTS_ERROR",
  ALL_PRODUCTS_CLEAR: "ALL_PRODUCTS_CLEAR",
};

/* For fetching one item details */

export const ONE_PRODUCT = {
  ONE_PRODUCT_LOADED: "ONE_PRODUCT_LOADED",
  ONE_PRODUCT_ERROR: "ONE_PRODUCT_ERROR",
  ONE_PRODUCT_CLEAR: "ONE_PRODUCT_CLEAR",
};

/* For buying item */

export const BUY_ITEM = {
  BUY_ITEM_SUCCESS: "BUY_ITEM_SUCCESS",
  BUY_ITEM_PROCESS_OVER: "BUY_ITEM_PROCESS_OVER",
  BUY_ITEM_ERROR: "BUY_ITEM_ERROR",
};

/* For canceling offer */

export const CANCEL_OFFER = {
  CANCEL_OFFER_SUCCESS: "CANCEL_OFFER_SUCCESS",
  CANCEL_OFFER_PROCESS_OVER: "CANCEL_OFFER_PROCESS_OVER",
  CANCEL_OFFER_ERROR: "CANCEL_OFFER_ERROR",
};

/* For fetching giving offers */

export const GIVEN_OFFERS = {
  GIVEN_OFFERS_LOADED: "GIVEN_OFFERS_LOADED",
  GIVEN_OFFERS_ERROR: "GIVEN_OFFERS_ERROR",
  GIVEN_OFFERS_CLEAR: "GIVEN_OFFERS_CLEAR",
};

/* For fetching received offers */

export const RECEIVED_OFFERS = {
  RECEIVED_OFFERS_LOADED: "RECEIVED_OFFERS_LOADED",
  RECEIVED_OFFERS_ERROR: "RECEIVED_OFFERS_ERROR",
  RECEIVED_OFFERS_CLEAR: "RECEIVED_OFFERS_CLEAR",
};

/* For fetching item options while adding new item */

export const FETCH_ITEM_OPTIONS = {
  COLOR_OPTIONS_LOADED: "COLOR_OPTIONS_LOADED",
  STATUS_OPTIONS_LOADED: "STATUS_OPTIONS_LOADED",
  CATEGORY_OPTIONS_LOADED: "CATEGORY_OPTIONS_LOADED",
  BRAND_OPTIONS_LOADED: "BRAND_OPTIONS_LOADED",
  ITEM_OPTIONS_ERROR: "ITEM_OPTIONS_ERROR",
};

/* For making offers */

export const MAKE_OFFER = {
  MAKE_OFFER_SENDED: "MAKE_OFFER_SENDED",
  MAKE_OFFER_PROCESS_OVER: "MAKE_OFFER_PROCESS_OVER",
  MAKE_OFFER_ERROR: "MAKE_OFFER_ERROR",
};

/* For adding new item */

export const ADD_ITEM = {
  ADD_ITEM_LOADING: "ADD_ITEM_LOADING",
  ADD_ITEM_LOADED: "ADD_ITEM_LOADED",
  ADD_ITEM_ERROR: "ADD_ITEM_ERROR",
  ADD_ITEM_RESET: "ADD_ITEM_RESET",
};

/* For rejecting offer */

export const REJECT_OFFER = {
  REJECT_OFFER_STATUS: "REJECT_OFFER_STATUS",
  REJECT_OFFER_ERROR: "REJECT_OFFER_ERROR",
  REJECT_OFFER_PROCESS_OVER: "REJECT_OFFER_PROCESS_OVER",
};

/* For accepting offer */

export const ACCEPT_OFFER = {
  ACCEPT_OFFER_STATUS: "ACCEPT_OFFER_STATUS",
  ACCEPT_OFFER_ERROR: "ACCEPT_OFFER_ERROR",
  ACCEPT_OFFER_PROCESS_OVER: "ACCEPT_OFFER_PROCESS_OVER",
};
